# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
   nightly:
      rustup_toolchain: nightly

steps:
- script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: Install rust
- script: rustup component add clippy
  displayName: Install Clippy
- script: cargo clippy --all
  displayName: Run clippy
- script: cargo build --all
  displayName: Cargo build
- script: cargo test --all
  displayName: Cargo test
